from setuptools import setup

setup(
    name='ecoinvent_row_report',
    version="0.1",
    packages=["ecoinvent_row_report"],
    author="Chris Mutel",
    author_email="cmutel@gmail.com",
    license=open('LICENSE.txt').read(),
    url="https://bitbucket.org/cmutel/ecoinvent-row-report",
    package_data={'ecoinvent_row_report': [
        "data/assets/css/*.*",
        "data/assets/fonts/*.*",
        "data/assets/js/*.*",
        "data/faces/*.*",
        "data/image/*.*",
        "data/templates/*.*",
    ]},
    install_requires=[
        "bw2regional",
        "constructive_geometries",
        "descartes",
        "fiona",
        "jinja2",
        "matplotlib",
        "pandarus",
        "pillow",
        "shapely",
    ],
    long_description=open('README.rst').read(),
    classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',
        'Operating System :: MacOS :: MacOS X',
        'Operating System :: Microsoft :: Windows',
        'Operating System :: POSIX',
        'Programming Language :: Python',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Scientific/Engineering :: Mathematics',
        'Topic :: Scientific/Engineering :: Visualization',
    ],
)
